language: php
sudo: false
services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

env:
  - DEPENDENCIES='dev' SYMFONY_VERSION='3.2.*@dev' DB=mysql

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS symfony;'
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:schema:update --env=test

script: phpunit