<?php

namespace AppBundle\Repository;

/**
 * RelationshipTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
